import {
  Heart,
  GraduationCap,
  Banknote,
  ShoppingCart,
  Factory,
  Building2,
  Plane,
  Hotel,
  HardHat,
  Landmark,
  Rocket,
  Building,
  HandHeart,
  ShoppingBag,
  Truck,
  Wifi,
} from "lucide-react";

export const industries = [
  {
    slug: "healthcare",
    name: "Healthcare",
    icon: Heart,
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80",
    description: "Digital solutions for hospitals, clinics, telemedicine, and health-tech platforms.",
    color: "from-red-500 to-pink-500",
    solutions: ["Hospital Management Systems", "Telemedicine Platforms", "Patient Portals", "EMR/EHR Systems"],
  },
  {
    slug: "education",
    name: "Education",
    icon: GraduationCap,
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80",
    description: "EdTech platforms, LMS, school management, and e-learning solutions.",
    color: "from-blue-500 to-indigo-500",
    solutions: ["Learning Management Systems", "School ERP", "E-Learning Platforms", "Student Portals"],
  },
  {
    slug: "finance",
    name: "Finance & Fintech",
    icon: Banknote,
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80",
    description: "Secure fintech applications, payment systems, and banking software.",
    color: "from-green-500 to-emerald-500",
    solutions: ["Payment Gateways", "Banking Software", "Investment Platforms", "Accounting Software"],
  },
  {
    slug: "retail",
    name: "Retail & E-Commerce",
    icon: ShoppingCart,
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&q=80",
    description: "Omnichannel retail platforms, inventory management, and customer experiences.",
    color: "from-orange-500 to-amber-500",
    solutions: ["E-Commerce Platforms", "Inventory Systems", "POS Solutions", "Customer Loyalty Apps"],
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    icon: Factory,
    image: "https://images.unsplash.com/photo-1565793298595-6a879b1d9492?w=600&q=80",
    description: "ERP systems, production tracking, quality management, and Industry 4.0 solutions.",
    color: "from-slate-500 to-gray-500",
    solutions: ["Manufacturing ERP", "Production Management", "Quality Control", "Supply Chain Systems"],
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    icon: Building2,
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=600&q=80",
    description: "Property management platforms, CRM, and real estate listing websites.",
    color: "from-violet-500 to-purple-500",
    solutions: ["Property Management", "Real Estate CRM", "Listing Platforms", "Virtual Tours"],
  },
  {
    slug: "travel",
    name: "Travel & Tourism",
    icon: Plane,
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&q=80",
    description: "Booking engines, travel management systems, and tourism platforms.",
    color: "from-sky-500 to-cyan-500",
    solutions: ["Booking Systems", "Travel Portals", "Tour Management", "Travel CRM"],
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    icon: Hotel,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    description: "Hotel management software, reservation systems, and guest experience platforms.",
    color: "from-yellow-500 to-amber-500",
    solutions: ["Hotel Management", "Reservation Systems", "Restaurant POS", "Guest Apps"],
  },
  {
    slug: "construction",
    name: "Construction",
    icon: HardHat,
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80",
    description: "Project management, contractor platforms, and construction ERP solutions.",
    color: "from-amber-600 to-orange-600",
    solutions: ["Project Management", "Construction ERP", "Site Management", "Contractor Portals"],
  },
  {
    slug: "government",
    name: "Government",
    icon: Landmark,
    image: "https://images.unsplash.com/photo-1541872703-74c5e44368f9?w=600&q=80",
    description: "Citizen service portals, e-governance platforms, and public sector solutions.",
    color: "from-blue-600 to-indigo-600",
    solutions: ["Citizen Portals", "E-Governance Systems", "Public Service Apps", "Document Management"],
  },
  {
    slug: "startups",
    name: "Startups",
    icon: Rocket,
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=600&q=80",
    description: "MVP development, product discovery, and technology partnerships for startups.",
    color: "from-purple-500 to-pink-500",
    solutions: ["MVP Development", "Product Strategy", "Tech Partnerships", "Growth Engineering"],
  },
  {
    slug: "enterprise",
    name: "Enterprise",
    icon: Building,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=80",
    description: "Enterprise-grade software, digital transformation, and IT modernization.",
    color: "from-gray-600 to-slate-600",
    solutions: ["Digital Transformation", "Legacy Modernization", "Enterprise Integration", "IT Strategy"],
  },
  {
    slug: "ngo",
    name: "NGOs & Non-Profits",
    icon: HandHeart,
    image: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&q=80",
    description: "Donation platforms, volunteer management, and impact tracking for NGOs.",
    color: "from-rose-500 to-pink-500",
    solutions: ["Donation Platforms", "Volunteer Management", "Impact Tracking", "Advocacy Websites"],
  },
  {
    slug: "ecommerce",
    name: "E-Commerce",
    icon: ShoppingBag,
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&q=80",
    description: "Full-stack e-commerce development from storefronts to backend fulfillment systems.",
    color: "from-teal-500 to-green-500",
    solutions: ["Online Stores", "Marketplace Platforms", "Subscription Commerce", "Headless Commerce"],
  },
  {
    slug: "logistics",
    name: "Logistics & Supply Chain",
    icon: Truck,
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80",
    description: "Fleet management, tracking platforms, and supply chain optimization solutions.",
    color: "from-blue-500 to-cyan-500",
    solutions: ["Fleet Management", "Tracking Systems", "Warehouse Management", "Last-Mile Delivery"],
  },
  {
    slug: "telecom",
    name: "Telecommunications",
    icon: Wifi,
    image: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&q=80",
    description: "Customer portals, billing systems, and OSS/BSS solutions for telecom providers.",
    color: "from-indigo-500 to-purple-500",
    solutions: ["Customer Portals", "Billing Systems", "Network Management", "OSS/BSS Solutions"],
  },
] as const;

export type Industry = (typeof industries)[number];
export type IndustrySlug = Industry["slug"];
