export const navigation = {
  main: [
    { label: "Home", href: "/" },
    {
      label: "Services",
      href: "/services",
      children: [
        { label: "Website Development", href: "/services/website-development" },
        { label: "Mobile App Development", href: "/services/mobile-app-development" },
        { label: "UI/UX Design", href: "/services/ui-ux-design" },
        { label: "Digital Marketing", href: "/services/digital-marketing" },
        { label: "SEO Services", href: "/services/seo" },
        { label: "Branding & Identity", href: "/services/branding" },
        { label: "AI Solutions", href: "/services/ai-solutions" },
        { label: "Custom Software", href: "/services/custom-software-development" },
        { label: "Cloud Solutions", href: "/services/cloud-solutions" },
        { label: "Data Solutions", href: "/services/data-solutions" },
        { label: "Cybersecurity", href: "/services/cybersecurity" },
        { label: "IT Infrastructure", href: "/services/it-infrastructure" },
        { label: "Backup & Recovery", href: "/services/backup-recovery" },
        { label: "Maintenance & Support", href: "/services/maintenance" },
      ],
    },
    { label: "Portfolio", href: "/portfolio" },
    { label: "About", href: "/about" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  footer: {
    company: [
      { label: "About Us", href: "/about" },
      { label: "Portfolio", href: "/portfolio" },
      { label: "Case Studies", href: "/case-studies" },
      { label: "Technologies", href: "/technologies" },
      { label: "Careers", href: "/careers" },
      { label: "Blog", href: "/blog" },
    ],
    services: [
      { label: "Website Development", href: "/services/website-development" },
      { label: "Mobile App Development", href: "/services/mobile-app-development" },
      { label: "UI/UX Design", href: "/services/ui-ux-design" },
      { label: "Digital Marketing", href: "/services/digital-marketing" },
      { label: "Cloud Solutions", href: "/services/cloud-solutions" },
      { label: "AI Solutions", href: "/services/ai-solutions" },
      { label: "Cybersecurity", href: "/services/cybersecurity" },
      { label: "View All Services", href: "/services" },
    ],
    support: [
      { label: "Contact Us", href: "/contact" },
      { label: "Support", href: "/support" },
      { label: "Book Consultation", href: "/book-consultation" },
      { label: "Request Quote", href: "/request-quote" },
      { label: "FAQ", href: "/faq" },
      { label: "Pricing", href: "/pricing" },
    ],
    legal: [
      { label: "Privacy Policy", href: "/privacy-policy" },
      { label: "Terms of Service", href: "/terms" },
      { label: "Refund Policy", href: "/refund-policy" },
      { label: "Cookie Policy", href: "/cookie-policy" },
      { label: "Sitemap", href: "/sitemap" },
    ],
  },
} as const;
