import {
  Globe,
  Smartphone,
  Palette,
  TrendingUp,
  Search,
  Paintbrush,
  Bot,
  Code2,
  Cloud,
  Database,
  Shield,
  Server,
  Wrench,
  HardDrive,
} from "lucide-react";

export const services = [
  {
    slug: "website-development",
    title: "Website Development",
    shortDesc: "Business, corporate, e-commerce, and custom web applications built for performance.",
    description:
      "From business websites to complex web applications, we design and develop digital experiences that convert visitors into customers.",
    icon: Globe,
    color: "from-blue-500 to-cyan-500",
    features: [
      "Business & Corporate Websites",
      "E-Commerce Websites",
      "CMS Websites (WordPress, Webflow)",
      "Custom Web Applications",
      "Progressive Web Apps (PWA)",
      "Landing Pages",
      "Portfolio Websites",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS"],
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development",
    shortDesc: "Cross-platform iOS and Android apps that delight users and drive engagement.",
    description:
      "We build high-performance mobile applications for iOS and Android using Flutter, React Native, and native technologies.",
    icon: Smartphone,
    color: "from-purple-500 to-pink-500",
    features: [
      "Android App Development",
      "iOS App Development",
      "Flutter Cross-Platform Apps",
      "React Native Apps",
      "Enterprise Mobile Applications",
      "App UI/UX Design",
      "App Store Optimization",
    ],
    technologies: ["Flutter", "React Native", "Swift", "Kotlin", "Firebase", "REST APIs"],
  },
  {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    shortDesc: "Beautiful, user-centered designs backed by research and tested for conversion.",
    description:
      "We create stunning interfaces grounded in user research, ensuring every interaction is intuitive, beautiful, and effective.",
    icon: Palette,
    color: "from-pink-500 to-rose-500",
    features: [
      "UI Design",
      "UX Research & Strategy",
      "Wireframes & Prototypes",
      "Dashboard Design",
      "Mobile App Design",
      "Design Systems",
      "Usability Testing",
    ],
    technologies: ["Figma", "Adobe XD", "Framer", "Principle", "Zeplin", "Storybook"],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    shortDesc: "Data-driven marketing campaigns that maximize ROI and accelerate business growth.",
    description:
      "Reach your ideal customers through targeted digital campaigns on Google, Meta, LinkedIn and beyond.",
    icon: TrendingUp,
    color: "from-orange-500 to-yellow-500",
    features: [
      "Google Ads (PPC)",
      "Meta Ads (Facebook & Instagram)",
      "LinkedIn Marketing",
      "Email Marketing Campaigns",
      "Content Marketing",
      "Lead Generation",
      "Marketing Analytics",
    ],
    technologies: ["Google Ads", "Meta Business", "HubSpot", "Mailchimp", "Analytics", "Semrush"],
  },
  {
    slug: "seo",
    title: "SEO Services",
    shortDesc: "Rank higher, get found faster, and drive qualified organic traffic to your business.",
    description:
      "Our comprehensive SEO strategies combine technical excellence with compelling content to dominate search rankings.",
    icon: Search,
    color: "from-green-500 to-emerald-500",
    features: [
      "Technical SEO",
      "On-Page & Off-Page SEO",
      "Local SEO",
      "Enterprise SEO",
      "SEO Audits",
      "Performance Optimization",
      "Core Web Vitals",
    ],
    technologies: ["Google Search Console", "Semrush", "Ahrefs", "Screaming Frog", "GA4", "GTM"],
  },
  {
    slug: "branding",
    title: "Branding & Identity",
    shortDesc: "Build a brand that stands out, tells your story, and earns instant recognition.",
    description:
      "We craft complete brand identities — from logo design to brand guidelines that maintain consistency across all touchpoints.",
    icon: Paintbrush,
    color: "from-yellow-500 to-amber-500",
    features: [
      "Logo Design",
      "Brand Identity & Guidelines",
      "Packaging Design",
      "Corporate Branding",
      "Social Media Branding",
      "Brand Strategy",
      "Visual Identity Systems",
    ],
    technologies: ["Adobe Illustrator", "Photoshop", "Figma", "InDesign", "After Effects"],
  },
  {
    slug: "ai-solutions",
    title: "AI Solutions",
    shortDesc: "Harness the power of AI to automate workflows, enhance products, and drive insights.",
    description:
      "We integrate cutting-edge AI and machine learning into your business processes to unlock efficiency and new capabilities.",
    icon: Bot,
    color: "from-violet-500 to-purple-500",
    features: [
      "AI Chatbots & Assistants",
      "GPT & LLM Integrations",
      "AI-Powered Automation",
      "Workflow Automation",
      "Business Process Automation",
      "Natural Language Processing",
      "AI Analytics & Insights",
    ],
    technologies: ["OpenAI", "LangChain", "TensorFlow", "Python", "HuggingFace", "Pinecone"],
  },
  {
    slug: "custom-software-development",
    title: "Custom Software Development",
    shortDesc: "Purpose-built software that fits your business perfectly — not the other way around.",
    description:
      "We develop bespoke software solutions including ERP, CRM, HRMS, and industry-specific platforms tailored to your exact needs.",
    icon: Code2,
    color: "from-cyan-500 to-blue-500",
    features: [
      "ERP Systems",
      "CRM Platforms",
      "HRMS Solutions",
      "Hospital Management Systems",
      "School Management Systems",
      "POS & Billing Software",
      "Inventory Management",
    ],
    technologies: ["React", "Node.js", "Python", "Java", ".NET", "PostgreSQL", "MongoDB"],
  },
  {
    slug: "cloud-solutions",
    title: "Cloud Solutions",
    shortDesc: "Scalable, secure cloud infrastructure on AWS, Azure, or Google Cloud — managed by experts.",
    description:
      "We architect, deploy, and manage cloud infrastructure that scales with your business while optimizing costs and performance.",
    icon: Cloud,
    color: "from-sky-500 to-indigo-500",
    features: [
      "AWS Solutions",
      "Microsoft Azure",
      "Google Cloud Platform",
      "Cloud Migration",
      "Docker & Kubernetes",
      "DevOps & CI/CD",
      "Infrastructure as Code",
    ],
    technologies: ["AWS", "Azure", "GCP", "Docker", "Kubernetes", "Terraform", "GitHub Actions"],
  },
  {
    slug: "data-solutions",
    title: "Data Solutions",
    shortDesc: "Transform raw data into strategic insights with robust analytics and BI solutions.",
    description:
      "From database design to business intelligence, we build data infrastructure that powers informed decision-making.",
    icon: Database,
    color: "from-teal-500 to-green-500",
    features: [
      "Database Design & Administration",
      "ETL & Data Warehousing",
      "Business Intelligence",
      "Data Analytics & Reporting",
      "Database Performance Tuning",
      "High Availability & DR",
      "Data Governance",
    ],
    technologies: ["PostgreSQL", "SQL Server", "MySQL", "Oracle", "MongoDB", "Power BI", "Tableau"],
  },
  {
    slug: "cybersecurity",
    title: "Cybersecurity",
    shortDesc: "Protect your business with enterprise-grade security assessments, monitoring, and compliance.",
    description:
      "We safeguard your digital assets through proactive security measures, penetration testing, and continuous monitoring.",
    icon: Shield,
    color: "from-red-500 to-rose-500",
    features: [
      "Vulnerability Assessment & VAPT",
      "Penetration Testing",
      "Security Audits",
      "Malware Removal",
      "SSL & Firewall Setup",
      "Security Monitoring",
      "Identity & Access Management",
    ],
    technologies: ["Nessus", "Metasploit", "Wireshark", "Burp Suite", "SIEM", "CrowdStrike"],
  },
  {
    slug: "it-infrastructure",
    title: "IT Infrastructure",
    shortDesc: "Reliable server, network, and virtualization infrastructure designed for business continuity.",
    description:
      "We design, deploy, and manage complete IT infrastructure including servers, networking, VPN, and Active Directory.",
    icon: Server,
    color: "from-slate-500 to-gray-500",
    features: [
      "Windows & Linux Server Setup",
      "Network Configuration",
      "VPN & Firewall Management",
      "Active Directory",
      "Virtualization (VMware/Hyper-V)",
      "Remote Support",
      "Server Monitoring",
    ],
    technologies: ["Windows Server", "Linux", "VMware", "Cisco", "Fortinet", "Active Directory"],
  },
  {
    slug: "backup-recovery",
    title: "Backup & Recovery",
    shortDesc: "Never lose critical data — automated backups and rapid recovery for business continuity.",
    description:
      "We implement comprehensive backup strategies and disaster recovery plans to ensure your data is always protected and recoverable.",
    icon: HardDrive,
    color: "from-amber-500 to-orange-500",
    features: [
      "Automated Backup Solutions",
      "Disaster Recovery Planning",
      "Database & Server Backup",
      "Cloud Backup (M365, Google Workspace)",
      "RAID & NAS Recovery",
      "Business Continuity Planning",
      "Recovery Testing",
    ],
    technologies: ["Veeam", "Acronis", "Azure Backup", "AWS Backup", "Zerto", "CommVault"],
  },
  {
    slug: "maintenance",
    title: "Maintenance & Support",
    shortDesc: "Keep your digital infrastructure running at peak performance with proactive maintenance.",
    description:
      "We provide ongoing maintenance, security updates, performance optimization, and 24/7 technical support for your systems.",
    icon: Wrench,
    color: "from-indigo-500 to-blue-500",
    features: [
      "Website Maintenance",
      "Server & Database Maintenance",
      "Security Updates & Patches",
      "Bug Fixes & Enhancements",
      "Performance Optimization",
      "24/7 Technical Support",
      "SLA-Backed Response Times",
    ],
    technologies: ["Monitoring Tools", "Uptime Robot", "Datadog", "PagerDuty", "Jira", "Slack"],
  },
] as const;

export type Service = (typeof services)[number];
export type ServiceSlug = Service["slug"];
